name       : thefuck
version    : '3.32'
release    : 18
source     :
    - https://github.com/nvbn/thefuck/archive/3.32.tar.gz : 76cbb014473672d1c384922857f8fbc1f6f7774f74f784149ad88751854ecfdf
license    : MIT
component  : system.utils
summary    : Magnificent app which corrects your previous console command
description: |
    Magnificent app which corrects your previous console command
builddeps  :
    - python-colorama  # Check.
    - python-decorator # Check.
    - python-psutil    # Check.
    - python-pyte      # Check.
    - python-pytest-mock # Check.
rundeps    :
    - python-colorama
    - python-decorator
    - python-psutil
    - python-pyte
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00755 $pkgfiles/thefuck.sh $installdir/usr/share/defaults/etc/profile.d/thefuck.sh
check      : |
    cd thefuck-%version%

    # Set environment variables to avoid writing into /root.
    # Also, disable tests that don't honor such env variables.
    %patch -p1 < $pkgfiles/0001-Set-XDG-variables-in-tests.patch
    python3 -m pytest --capture=sys -k 'not test_get_all_executables_exclude_paths' tests
