name       : thefuck
version    : '3.30'
release    : 15
source     :
    - https://github.com/nvbn/thefuck/archive/3.30.tar.gz : dd2e7bc94e9453beabbafc10c4d62c67601ea705250103a67ababcdad2991dd3
license    : MIT
component  : system.utils
summary    : Magnificent app which corrects your previous console command
description: |
    Magnificent app which corrects your previous console command
rundeps    :
    - python-colorama
    - python-decorator
    - python-psutil
    - python-pyte
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00755 $pkgfiles/thefuck.sh $installdir/usr/share/defaults/etc/profile.d/thefuck.sh
