name       : thefuck
version    : '3.28'
release    : 12
source     :
    - https://github.com/nvbn/thefuck/archive/3.28.tar.gz : b5c83e380e4af90d49ab01a55a326e608875bedb981bc7dae9b6a4b72cc521c4
license    : MIT
component  : system.utils
summary    : Magnificent app which corrects your previous console command
description: |
    Magnificent app which corrects your previous console command
rundeps    :
    - python-colorama
    - python-decorator
    - python-psutil
    - python-pyte
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m 00755 $pkgfiles/thefuck.sh $installdir/usr/share/defaults/etc/profile.d/thefuck.sh
