name       : thefuck
version    : 3.23
release    : 6
source     :
    - https://github.com/nvbn/thefuck/archive/3.23.tar.gz : 36b0af52219a56dc34bb085e75afa822c479c5c05b9393598effc2c1b3c5eb32
license    : MIT
component  : system.utils
summary    : Magnificent app which corrects your previous console command
description: |
    Magnificent app which corrects your previous console command
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python3-decorator
    - python-psutil
    - python-six
    - python-colorama
build      : |
    %python3_setup
install    : |-
    %python3_install
    install -D -m 00755 $pkgfiles/thefuck.sh $installdir/usr/share/defaults/etc/profile.d/thefuck.sh
