name       : thefuck
version    : '3.24'
release    : 8
source     :
    - https://github.com/nvbn/thefuck/archive/3.24.tar.gz : 686867f264ee34d9287814dde0e9ca5debb322deeaf0ac6773ec06f823d7c0b4
license    : MIT
component  : system.utils
summary    : Magnificent app which corrects your previous console command
description: |
    Magnificent app which corrects your previous console command
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python-colorama
    - python-psutil
    - python-pyte
    - python-six
    - python3-decorator
build      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m 00755 $pkgfiles/thefuck.sh $installdir/usr/share/defaults/etc/profile.d/thefuck.sh
