name       : thefuck
version    : '3.14'
release    : 3
source     :
    - https://github.com/nvbn/thefuck/archive/3.14.tar.gz : 5757d7ba05ead08e867ab6b41e34d6f27fe38d5bb8af1ffc097aeed5ccc9c72f
license    : MIT
component  : system.utils
summary    : Magnificent app which corrects your previous console command
description: |
    Magnificent app which corrects your previous console command
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python-psutil
    - python-six
    - python3-colorama
    - python3-decorator
build      : |
    %python3_setup
install    : |-
    %python3_install
    install -D -m 00755 $pkgfiles/thefuck.sh $installdir/usr/share/defaults/etc/profile.d/thefuck.sh
